{% set name = "cytosim" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89746bbc18963aaf4eaa52e4e0e9c1bceaa205bb171f433f89c9ad551e873aac
build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - pip
    - cmake >=3.14
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libblas
    - liblapack
    - pybind11
    - ncurses
  host:
    - pip
    - setuptools
    - python
    - libblas
    - liblapack
    - pybind11
    - ncurses
  run:
    - python
    - libblas
    - liblapack
    - pybind11

test:
  imports:
    - cytosim2D
about:
  home: http://cytosim.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Cytosim: Langevin dynamics of active polymer networks"
  doc_url: https://cytosim.gitlab.io/cytosim/doc/code/doxygen/index.html
  dev_url: https://gitlab.com/f-nedelec/cytosim

extra:
  recipe-maintainers:
    - SergeDmi
